import '~/styles/globals.css';
import { Layout } from '@components/layout/Layout';

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-background text-white min-h-screen">
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
